# scheduler class for distributing the topology for execution
heron.class.scheduler:                       com.twitter.heron.scheduler.ecs.EcsScheduler

# launcher class for submitting and launching the topology
heron.class.launcher:                        com.twitter.heron.scheduler.ecs.EcsLauncher

# location of java - pick it up from shell environment
heron.directory.sandbox.java.home:           ${JAVA_HOME}
